apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-prod

resources:
- ../../base

replicas:
- count: 3
  name: frontend
images:
- name: sammylin6525/gitops-frontend
  newName: sammylin6525/frontend
  newTag: 9ad4d208d6c5d3150f298aaefc7e7a079757ccf3
