apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-prod

resources:
- ../../base

replicas:
- count: 3
  name: backend
images:
- name: sammylin6525/backend
  newName: sammylin6525/backend
  newTag: 76d42b8f9e77c66757d6778d9685c1ea3cf02865
