apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-dev

resources:
- ../../base

replicas:
- count: 2
  name: frontend
images:
- name: sammylin6525/frontend
  newName: sammylin6525/frontend
  newTag: 3d2643a405985a7eedb1d98624afb3a6b72ea341
