apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-dev

resources:
- ../../base

replicas:
- count: 2
  name: frontend
images:
- name: sammylin6525/frontend
  newName: sammylin6525/frontend
  newTag: 76d42b8f9e77c66757d6778d9685c1ea3cf02865
