apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sammyCHY/Mini_Project-Advanced_GitOps_Techniques.git
    targetRevision: main
    path: kubernetes/backend/overlays/dev

  destination:
    name: cluster-dev
    namespace: backend-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true