apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-project
  namespace: argocd

spec:
  description: GitOps Demo Project

  sourceRepos:
    - 'https://github.com/<YOUR_GITHUB_USERNAME>/gitops-project.git'

  destinations:
    - namespace: gitops-dev
      server: https://kubernetes.default.svc

    - namespace: gitops-prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'